
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { ExtendedDatabase } from './schema';

const SUPABASE_URL = "https://tiouzxdxlxptissfnktw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRpb3V6eGR4bHhwdGlzc2Zua3R3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk1NjA0ODMsImV4cCI6MjA1NTEzNjQ4M30.TQZNfD9IJMc_cDq3qg_ODcl5uFN5TvUudH_gdk3GqrI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<ExtendedDatabase>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
    }
  }
);
